#!/usr/bin/env npx tsx
/**
 * Compile SQL migration files into a TypeScript module that can be
 * imported by the worker at runtime. This avoids filesystem access
 * on Cloudflare Workers.
 *
 * Usage: npx tsx scripts/compile-migrations.ts
 * Output: src/migrations-compiled.ts
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, basename } from 'node:path'

const MIGRATIONS_ROOT = join(import.meta.dirname ?? __dirname, '..', 'migrations')
const OUTPUT = join(import.meta.dirname ?? __dirname, '..', 'src', 'migrations-compiled.ts')

interface Migration {
  name: string
  sql: string
}

interface DatabaseMigrations {
  binding: string
  migrations: Migration[]
}

const databases: DatabaseMigrations[] = []

for (const dir of ['analytics', 'core', 'marketing']) {
  const dirPath = join(MIGRATIONS_ROOT, dir)
  const files = readdirSync(dirPath).filter(f => f.endsWith('.sql')).sort()

  const migrations: Migration[] = files.map(file => ({
    name: basename(file, '.sql'),
    sql: readFileSync(join(dirPath, file), 'utf-8').trim(),
  }))

  const binding = dir === 'analytics' ? 'DB_ANALYTICS'
    : dir === 'core' ? 'DB_CORE'
    : 'DB_MARKETING'

  databases.push({ binding, migrations })
}

const output = `// Auto-generated by scripts/compile-migrations.ts — do not edit manually
// Generated: ${new Date().toISOString()}

export interface CompiledMigration {
  name: string
  sql: string
}

export interface DatabaseMigrations {
  binding: 'DB_ANALYTICS' | 'DB_CORE' | 'DB_MARKETING'
  migrations: CompiledMigration[]
}

export const compiledMigrations: DatabaseMigrations[] = ${JSON.stringify(databases, null, 2)}
`

writeFileSync(OUTPUT, output)

const totalMigrations = databases.reduce((sum, db) => sum + db.migrations.length, 0)
console.log(`Compiled ${totalMigrations} migrations across ${databases.length} databases → ${OUTPUT}`)
