/**
 * Inkwell instance config — generated by `sos init`.
 *
 * Placeholders (replaced at init time):
 *   {{SLUG}}      — URL-safe identifier (e.g. "acme")
 *   {{LABEL}}     — Human-readable name (e.g. "Acme Co")
 *   {{DOMAIN}}    — Custom domain (e.g. "acme.com")
 *   {{EMAIL}}     — Owner email
 *   {{INDUSTRY}}  — Industry hint (e.g. "consulting")
 *   {{TAGLINE}}   — One-line tagline
 */
import { config as base } from '../../inkwell.config'

export const config = {
  ...base,
  name: '{{LABEL}}',
  domain: '{{DOMAIN}}',
  tagline: '{{TAGLINE}}',

  network: {
    ...base.network,
    // Phase 4 v0.9.3 — all Inkwell instances share the single-ingress
    // edge Worker at api.mumega.com. Tenant is identified via Bearer token.
    apiUrl: 'https://api.mumega.com',
    storageKeyPrefix: '{{SLUG}}',
    brandName: '{{LABEL}}',
    poweredByUrl: 'https://{{DOMAIN}}',
    busTarget: '{{SLUG}}',
  },

  adapters: {
    bus: 'sos',
    memory: 'mirror',
    economy: 'sos',
    agent: 'd1',
    graph: 'd1',
  },

  seo: {
    ...base.seo,
    organization: {
      ...base.seo.organization,
      name: '{{LABEL}}',
      url: 'https://{{DOMAIN}}',
      knowsAbout: ['{{INDUSTRY}}'],
    },
    defaultAuthor: { name: '{{LABEL}}', url: 'https://{{DOMAIN}}' },
  },

  workerUrl: 'https://api.mumega.com',
} as const
