/**
 * Inkwell instance config — generated by `sos init`.
 *
 * Placeholders (replaced at init time):
 *   acme      — URL-safe identifier (e.g. "acme")
 *   Acme Co     — Human-readable name (e.g. "Acme Co")
 *       — Custom domain (e.g. "acme.com")
 *   owner@acme.com     — Owner email
 *     — Industry hint (e.g. "consulting")
 *      — One-line tagline
 */
import { config as base } from '../../inkwell.config'

export const config = {
  ...base,
  name: 'Acme Co',
  domain: '',
  tagline: '',

  network: {
    ...base.network,
    apiUrl: 'https://api.',
    storageKeyPrefix: 'acme',
    brandName: 'Acme Co',
    poweredByUrl: 'https://',
    busTarget: 'acme',
  },

  adapters: {
    bus: 'sos',
    memory: 'mirror',
    economy: 'sos',
    agent: 'd1',
    graph: 'd1',
  },

  seo: {
    ...base.seo,
    organization: {
      ...base.seo.organization,
      name: 'Acme Co',
      url: 'https://',
      knowsAbout: [''],
    },
    defaultAuthor: { name: 'Acme Co', url: 'https://' },
  },

  workerUrl: 'https://api.',
} as const
